$schema: https://json-schema.org/draft/2020-12/schema
description: 'Basic-YPR: Basic GeoPose using yaw, pitch, and roll to specify orientation'
type: object
properties:
  position:
    $ref: ../position.schema.yaml
    x-jsonld-id: http://example.com/geopose/position
  angles:
    $ref: ../angles.schema.yaml
    x-jsonld-id: http://example.com/geopose/angles
required:
- position
- angles
