"$schema": https://json-schema.org/draft/2020-12/schema
description: 'Basic-YPR: Basic GeoPose using yaw, pitch, and roll to specify orientation'
'@modelReference': ../context.jsonld
type: object
properties:
  position:
    "$ref": ../position.schema.yaml
  angles:
    "$ref": ../angles.schema.yaml
required:
  - position
  - angles
