name: Process Building Blocks

on:
  push:
    branches: [master]
  pull_request:
    types: closed
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Run postprocessing
        run: |
          python -m pip install -U pip
          pip install -r scripts/requirements.txt
          python -m scripts.postprocess registerv3.json registereditems/ -s metadata-schema.yaml \
            -u https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}
          docker run --rm -v $(pwd)/generateddocs/slate:/srv/slate/source \
            -v $(pwd)/generateddocs/slate-build:/srv/slate/build slatedocs/slate build
          python -m ogc.na.ingest_json -t -j --batch registerv3.json
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          message: Building blocks postprocessing

  deploy-gh-pages:
    needs: build
    uses: ./.github/workflows/deploy-gh-pages.yml
